
name: Android APK Builder
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Generate Gradle Wrapper
        run: |
          # Fix missing gradle files
          gradle wrapper --gradle-version 8.1.1
          chmod +x gradlew
          
      - name: Verify Files
        run: |
          ls -la
          ls -la gradle/wrapper/
          
      - name: Build APK
        run: |
          ./gradlew assembleDebug --stacktrace --no-daemon
          
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: binance-signal-bot
          path: |
            app/build/outputs/apk/debug/app-debug.apk
            app/build/outputs/apk/debug/output-metadata.json
